services:
  storage_consumer_welcome:
    build:
      context: .
      dockerfile: ./storage_consumers/welcome/Dockerfile
    env_file:
      - ./.env

  storage_consumer_bookmarks:
    build:
      context: .
      dockerfile: ./storage_consumers/bookmarks/Dockerfile
    env_file:
      - ./.env

  worker_email:
    build:
      context: .
      dockerfile: workers/worker_email/Dockerfile
    env_file:
      - ./.env