"""Initial migration.

Revision ID: 3a05732e2d4c
Revises: 
Create Date: 2022-03-15 12:35:26.135248

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3a05732e2d4c"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "auth_history", ["id", "platform"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "auth_history", type_="unique")
    # ### end Alembic commands ###
